package oop

class Customer1(val name: String) {

    // generated by IntelliJ
    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (javaClass != other?.javaClass) return false

        other as Customer1

        if (name != other.name) return false

        return true
    }

    // generated by IntelliJ
    override fun hashCode(): Int {
        return name.hashCode()
    }
}